// GERADO por tools/import-sounds.py — não editar à mão.
// Efeitos sonoros CC0 (OpenGameArt: Independent.nu, qubodup, StarNinjas, artisticdude; Kenney). Cada nome
// tem variações; o AudioManager sorteia uma. Nomes fora daqui continuam sintetizados.
export const SOUND_FILES = {
  punch: ['sounds/punch_0.ogg', 'sounds/punch_1.ogg', 'sounds/punch_2.ogg', 'sounds/punch_3.ogg', 'sounds/punch_4.ogg', 'sounds/punch_5.ogg', 'sounds/punch_6.ogg', 'sounds/punch_7.ogg'],
  heavyPunch: ['sounds/heavyPunch_0.ogg', 'sounds/heavyPunch_1.ogg', 'sounds/heavyPunch_2.ogg', 'sounds/heavyPunch_3.ogg', 'sounds/heavyPunch_4.ogg', 'sounds/heavyPunch_5.ogg'],
  kick: ['sounds/kick_0.ogg', 'sounds/kick_1.ogg', 'sounds/kick_2.ogg', 'sounds/kick_3.ogg', 'sounds/kick_4.ogg'],
  impact: ['sounds/impact_0.ogg', 'sounds/impact_1.ogg', 'sounds/impact_2.ogg', 'sounds/impact_3.ogg', 'sounds/impact_4.ogg'],
  bladeHit: ['sounds/bladeHit_0.ogg', 'sounds/bladeHit_1.ogg', 'sounds/bladeHit_2.ogg', 'sounds/bladeHit_3.ogg'],
  slashFinal: ['sounds/slashFinal_0.ogg', 'sounds/slashFinal_1.ogg'],
  axeHit: ['sounds/axeHit_0.ogg', 'sounds/axeHit_1.ogg'],
  swing: ['sounds/swing_0.ogg', 'sounds/swing_1.ogg', 'sounds/swing_2.ogg', 'sounds/swing_3.ogg', 'sounds/swing_4.ogg', 'sounds/swing_5.ogg', 'sounds/swing_6.ogg'],
  blade: ['sounds/blade_0.ogg', 'sounds/blade_1.ogg', 'sounds/blade_2.ogg', 'sounds/blade_3.ogg', 'sounds/blade_4.ogg', 'sounds/blade_5.ogg'],
  blockHit: ['sounds/blockHit_0.ogg', 'sounds/blockHit_1.ogg', 'sounds/blockHit_2.ogg', 'sounds/blockHit_3.ogg', 'sounds/blockHit_4.ogg'],
  guardBreak: ['sounds/guardBreak_0.ogg', 'sounds/guardBreak_1.ogg', 'sounds/guardBreak_2.ogg', 'sounds/guardBreak_3.ogg', 'sounds/guardBreak_4.ogg'],
  perfectBlock: ['sounds/perfectBlock_0.ogg', 'sounds/perfectBlock_1.ogg', 'sounds/perfectBlock_2.ogg'],
  m4: ['sounds/m4_0.ogg', 'sounds/m4_1.ogg', 'sounds/m4_2.ogg', 'sounds/m4_3.ogg'],
  shotgun: ['sounds/shotgun_0.ogg', 'sounds/shotgun_1.ogg', 'sounds/shotgun_2.ogg', 'sounds/shotgun_3.ogg', 'sounds/shotgun_4.ogg', 'sounds/shotgun_5.ogg', 'sounds/shotgun_6.ogg', 'sounds/shotgun_7.ogg'],
  sniper: ['sounds/sniper_0.ogg', 'sounds/sniper_1.ogg', 'sounds/sniper_2.ogg', 'sounds/sniper_3.ogg', 'sounds/sniper_4.ogg', 'sounds/sniper_5.ogg', 'sounds/sniper_6.ogg', 'sounds/sniper_7.ogg'],
  clawHit: ['sounds/clawHit_0.ogg', 'sounds/clawHit_1.ogg'],
  bloodClaw: ['sounds/bloodClaw_0.ogg', 'sounds/bloodClaw_1.ogg'],
  descarnar: ['sounds/descarnar_0.ogg', 'sounds/descarnar_1.ogg'],
  chainThrow: ['sounds/chainThrow_0.ogg', 'sounds/chainThrow_1.ogg'],
  chainPull: ['sounds/chainPull_0.ogg', 'sounds/chainPull_1.ogg'],
  whip: ['sounds/whip_0.ogg', 'sounds/whip_1.ogg'],
  teleport: ['sounds/teleport_0.ogg'],
  blink: ['sounds/blink_0.ogg'],
  fearGaze: ['sounds/fearGaze_0.ogg', 'sounds/fearGaze_1.ogg'],
  heartbeat: ['sounds/heartbeat_0.ogg'],
  land: ['sounds/land_0.ogg'],
  jump: ['sounds/jump_0.ogg', 'sounds/jump_1.ogg'],
  ko: ['sounds/ko_0.ogg', 'sounds/ko_1.ogg'],
  ritual: ['sounds/ritual_0.ogg', 'sounds/ritual_1.ogg'],
  carga: ['sounds/carga_0.ogg', 'sounds/carga_1.ogg', 'sounds/carga_2.ogg'],
  armed: ['sounds/armed_0.ogg'],
  specialStart: ['sounds/specialStart_0.ogg', 'sounds/specialStart_1.ogg'],
  powerUp: ['sounds/powerUp_0.ogg', 'sounds/powerUp_1.ogg', 'sounds/powerUp_2.ogg'],
  drain: ['sounds/drain_0.ogg', 'sounds/drain_1.ogg'],
  rebirth: ['sounds/rebirth_0.ogg'],
  fearBlade: ['sounds/fearBlade_0.ogg', 'sounds/fearBlade_1.ogg'],
  maskOn: ['sounds/maskOn_0.ogg'],
  smoke: ['sounds/smoke_0.ogg', 'sounds/smoke_1.ogg', 'sounds/smoke_2.ogg'],
  banner: ['sounds/banner_0.ogg', 'sounds/banner_1.ogg'],
  laugh: ['sounds/laugh_0.ogg'],
  applause: ['sounds/applause_0.ogg'],
  chargeHum: ['sounds/chargeHum_0.ogg'],
  knifeThrow: ['sounds/knifeThrow_0.ogg', 'sounds/knifeThrow_1.ogg', 'sounds/knifeThrow_2.ogg'],
  trapSnap: ['sounds/trapSnap_0.ogg'],
  grenadePin: ['sounds/grenadePin_0.ogg'],
  reload: ['sounds/reload_0.ogg'],
  explosion: ['sounds/explosion_0.ogg', 'sounds/explosion_1.ogg', 'sounds/explosion_2.ogg', 'sounds/explosion_3.ogg', 'sounds/explosion_4.ogg', 'sounds/explosion_5.ogg', 'sounds/explosion_6.ogg'],
  shockwave: ['sounds/shockwave_0.ogg', 'sounds/shockwave_1.ogg'],
  select: ['sounds/select_0.ogg', 'sounds/select_1.ogg', 'sounds/select_2.ogg', 'sounds/select_3.ogg'],
  confirm: ['sounds/confirm_0.ogg', 'sounds/confirm_1.ogg'],
  denied: ['sounds/denied_0.ogg', 'sounds/denied_1.ogg', 'sounds/denied_2.ogg', 'sounds/denied_3.ogg'],
  tick: ['sounds/tick_0.ogg', 'sounds/tick_1.ogg'],
  button: ['sounds/button_0.ogg', 'sounds/button_1.ogg', 'sounds/button_2.ogg'],
};
